apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sample-app
  name: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sample-app
    spec:
      imagePullSecrets:
      - name: mydocker
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - image: nagsg1996/devops-stuff:my-sample-app-main-8e1a5967-24-12-2025-052745-68
        name: devops-stuff
        ports:
        - containerPort: 8123
        resources: {}
status: {}
